siteTitle: richardmands.com
title: Richard Mands
subTitle: Full-Stack Developer
introHeading: Please allow me to introduce myself...
introBody: |+
  I'm a full-stack developer with primary experience in JavaScript. I'm proficient with a JS stack based around React, Redux, Node, Express and Webpack. I've also worked with a variety of other React adjacent technologies such as MongoDB, Mongoose, Gatsby, Parcel, Flux, etc, as well as Ruby (Rails, Sinatra) AWS (Lambda, SNS/SQS, Serverless) and have experience of technologies such as Socket.io, DynamoDB, Firebase, Google APIs and others.

  A quick study who has learned how to learn, I have a strong leadership background, adapt easily to new technologies and bring with me a real passion for what I do, a fierce work-ethic and an honest desire to leave the world a better place each day.

  I am currently working as a Lead Software Engineer at Bede Gaming . Prior to that I was a Software Engineer at Sage and previously spent 3 years coding, designing and marketing as co-founder of Cinderhouse Creative.

  Through Cinderhouse Creative, I was a co-founder / developer of Eduku, a social enterprise (self-funded charity), that aimed to raise funds for those lacking educational opportunities in low-income countries via an online learning platform.

  I was also part of the team that won Cisco's first prize at AngelHack's Lady Problems hackathon in San Francisco in October 2016 for creating Entable (an sms-based online banking platform aimed specifically at supporting women in low-income countries by offering wider access to microfinance).
